name: Build & Deploy Angular to GitHub Pages

# 1) Permisos mínimos para que el paso de Pages funcione
permissions:
  contents: read       # para checkout
  pages: write         # para publicar en Pages
  id-token: write      # requerido por actions/deploy-pages

# 2) Se dispara al pushear a master (o cámbialo a main si lo prefieres)
on:
  push:
    branches:
      - master

jobs:
  # 3) Etapa de build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (production)
        run: npm run build -- \
          --configuration production \
          --output-path=dist \
          --base-href="/GameOfLife/"

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/browser   # aquí es donde está tu index.html y assets

  # 4) Etapa de deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages   # vincula el entorno Pages en tu repo
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
